site_name: Slate EV Truck API
site_description: Documentation for the Slate EV Truck API
site_author: Slate EV Team

# Repository
repo_name: slate-ev-fan-api
repo_url: https://github.com/yourusername/slate-ev-fan-api

# Theme
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

# Page tree
nav:
  - Home: index.md
  - API Reference:
    - Overview: api/overview.md
    - Endpoints: api/endpoints.md
    - Models: api/models.md
  - Guides:
    - Getting Started: guides/getting-started.md
    - Deployment: guides/deployment.md
  - Development:
    - Environment Setup: development/environment-setup.md
    - Contributing: development/contributing.md

# Plugins
plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [..]
          options:
            show_source: true
